version: '3.7'
services:

    Block explorer server
  electrum:
    build:
      context: ./provisioning/mempool/electrum
    container_name: electrum
    ports:
      - 50001:50001
      - 30000:30000
    volumes:
      - ./provisioning/mempool/electrum/config.toml:/etc/electrs/config.toml
      - ./provisioning/mempool/electrum/config.toml:/.electrs/config.toml
      - ./provisioning/mempool/electrum/config.toml:/electrs.toml
      - ./volumes/bitcoin/:/config
    restart: unless-stopped
    networks:
      - stacks-blockchain

  web:
    build:
      context: ./provisioning/mempool/frontend
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8083:80"
    environment:
      FRONTEND_HTTP_PORT: "8083"
      BACKEND_MAINNET_HTTP_HOST: "api"
    networks:
      - stacks-blockchain
      
  api:
    build:
      context: ./provisioning/mempool/backend
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
    environment:
      RPC_HOST: "bitcoin"
      RPC_PORT: "18443"
      RPC_USER: "blockstack"
      RPC_PASS: "blockstacksystem"
      ELECTRUM_HOST: "electrum"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS: "false"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASS: "mempool"
      BACKEND_MAINNET_HTTP_PORT: "8999"
      CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
    networks:
      - stacks-blockchain

  db:
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./provisioning/mempool/mysql/data:/var/lib/mysql
      - ./provisioning/mempool/mysql/script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    networks:
      - stacks-blockchain

networks:
  stacks-blockchain:
    external: true