[network]
name = "testnet"
node_rpc_address = "http://localhost:20443"

[accounts.deployer]
mnemonic = "iron lizard museum crumble you focus damage surprise job loud genuine stamp replace scan muscle away junior know perfect manual update artwork hospital ivory"
balance = 10_000_000_000_000

[accounts.wallet_1]
mnemonic = "depend easy tortoise audit mass canyon soon swarm burger shiver fiber excite seminar glad dream minor inmate scatter civil punch disagree candy system one"
balance = 10_000_000_000_000

[accounts.wallet_2]
mnemonic = "check magnet wheel ring helmet cream call income arrest above surge occur capital useless clog brass draft circle deposit athlete promote gather sentence betray"
balance = 10_000_000_000_000

[accounts.wallet_3]
mnemonic = "warm security impulse alert erode human disagree foot police power subject segment various behind raise crime amazing wing exact crouch clog what stumble small"
balance = 10_000_000_000_000