version: '3.7'
services:
  bitcore:
    build:
      context: ./provisioning/bitcore
      dockerfile: Dockerfile
    ports:
      - 8100:8100
      - 3002:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore-test
      - BITCORE_CONFIG_PATH=/bitcore/bitcore.config.json
    volumes:
      - ./provisioning/bitcore/config.json:/bitcore/bitcore.config.json
    depends_on:
      - db
      - bitcoin
    networks:
      - stacks-blockchain
    command: "npm run node"
  db:
    image: mongo
    networks:
      - stacks-blockchain


networks:
  stacks-blockchain:
    external: true