version: '3.7'
services:

  bitcoin-explorer:
    build:
      context: ./provisioning/explorer
    restart: on-failure
    ports:
      - "8001:8001"
    environment:
      BTCEXP_BITCOIND_HOST: bitcoin.stacks-blockchain
      BTCEXP_BITCOIND_USER: blockstack
      BTCEXP_BITCOIND_PASS: blockstacksystem
      BTCEXP_BITCOIND_PORT: 28443
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_PORT: 8001
    networks:
      - stacks-blockchain

networks:
  stacks-blockchain:
    external: true