version: '3.7'
services:
  bns-data:
    build:
      context: ./provisioning/private-testnet/bns
    container_name: bns_data
    volumes:
      - ./provisioning/private-testnet/bns-data:/bns-data
    environment:
      - BNS_IMPORT_DIR=/bns-data