[project]
name = "clarinet"

[contracts.arkadiko-dao-token-trait-v1]
depends_on = []
path = "contracts/external/arkadiko/arkadiko-dao-token-trait-v1.clar"

[contracts.arkadiko-collateral-types-v1-1]
depends_on = ["arkadiko-collateral-types-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-collateral-types-v1-1.clar"

[contracts.arkadiko-dao]
depends_on = ["arkadiko-token", "arkadiko-collateral-types-v1-1", "arkadiko-vault-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-dao.clar"

[contracts.arkadiko-governance-v1-1]
depends_on = ["arkadiko-token", "stdiko-token", "sip-010-trait-ft-standard", "arkadiko-stake-pool-diko-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-governance-v1-1.clar"

[contracts.arkadiko-token]
depends_on = ["sip-010-trait-ft-standard", "arkadiko-dao-token-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-token.clar"

[contracts.arkadiko-oracle-trait-v1]
depends_on = []
path = "contracts/external/arkadiko/arkadiko-oracle-trait-v1.clar"

[contracts.arkadiko-oracle-v1-1]
depends_on = ["arkadiko-oracle-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-oracle-v1-1.clar"

[contracts.arkadiko-vault-data-v1-1]
depends_on = ["arkadiko-diko-guardian-v1-1"]
path = "contracts/external/arkadiko/arkadiko-vault-data-v1-1.clar"

[contracts.arkadiko-diko-guardian-v1-1]
depends_on = ["arkadiko-token"]
path = "contracts/external/arkadiko/arkadiko-diko-guardian-v1-1.clar"

[contracts.arkadiko-auction-engine-v1-1]
depends_on = [
  "arkadiko-oracle-v1-1",
  "usda-token",
  "arkadiko-freddie-v1-1",
  "sip-010-trait-ft-standard",
  "arkadiko-vault-trait-v1",
  "arkadiko-auction-engine-trait-v1"
]
path = "contracts/external/arkadiko/arkadiko-auction-engine-v1-1.clar"

[contracts.arkadiko-freddie-v1-1]
depends_on = [
  "arkadiko-collateral-types-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-trait-v1",
  "arkadiko-oracle-trait-v1",
  "sip-010-trait-ft-standard",
  "arkadiko-vault-manager-trait-v1",
  "arkadiko-sip10-reserve-v1-1",
  "arkadiko-vault-data-v1-1",
  "arkadiko-vault-rewards-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-freddie-v1-1.clar"

[contracts.arkadiko-liquidator-v1-1]
depends_on = ["arkadiko-collateral-types-v1-1", "arkadiko-dao", "arkadiko-vault-manager-trait-v1", "arkadiko-auction-engine-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-liquidator-v1-1.clar"

[contracts.arkadiko-sip10-reserve-v1-1]
depends_on = [
  "arkadiko-collateral-types-v1-1",
  "sip-010-trait-ft-standard",
  "arkadiko-vault-trait-v1",
  "arkadiko-oracle-trait-v1",
  "arkadiko-oracle-v1-1",
  "arkadiko-dao",
  "usda-token",
  "xstx-token"
]
path = "contracts/external/arkadiko/arkadiko-sip10-reserve-v1-1.clar"

[contracts.arkadiko-stacker-v1-1]
depends_on = [
  "arkadiko-vault-data-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-rewards-v1-1",
  "arkadiko-freddie-v1-1",
  "arkadiko-stacker-payer-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-stacker-v1-1.clar"

[contracts.arkadiko-stacker-payer-v1-1]
depends_on = [
  "arkadiko-vault-data-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-rewards-v1-1",
  "arkadiko-freddie-v1-1",
  "arkadiko-swap-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-stacker-payer-v1-1.clar"

[contracts.arkadiko-mock-stacker-v1-1]
depends_on = ["arkadiko-vault-data-v1-1", "arkadiko-stx-reserve-v1-1", "arkadiko-vault-rewards-v1-1"]
path = "contracts/external/arkadiko/arkadiko-mock-stacker-v1-1.clar"

[contracts.arkadiko-stacker-2-v1-1]
depends_on = [
  "arkadiko-vault-data-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-rewards-v1-1",
  "arkadiko-freddie-v1-1",
  "arkadiko-stacker-payer-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-stacker-2-v1-1.clar"

[contracts.arkadiko-stacker-3-v1-1]
depends_on = [
  "arkadiko-vault-data-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-rewards-v1-1",
  "arkadiko-freddie-v1-1",
  "arkadiko-stacker-payer-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-stacker-3-v1-1.clar"

[contracts.arkadiko-stacker-4-v1-1]
depends_on = [
  "arkadiko-vault-data-v1-1",
  "arkadiko-stx-reserve-v1-1",
  "arkadiko-vault-rewards-v1-1",
  "arkadiko-freddie-v1-1",
  "arkadiko-stacker-payer-v1-1"
]
path = "contracts/external/arkadiko/arkadiko-stacker-4-v1-1.clar"

[contracts.arkadiko-stx-reserve-v1-1]
depends_on = [
  "arkadiko-collateral-types-v1-1",
  "arkadiko-oracle-v1-1",
  "arkadiko-dao",
  "usda-token",
  "sip-010-trait-ft-standard",
  "arkadiko-vault-trait-v1"
]
path = "contracts/external/arkadiko/arkadiko-stx-reserve-v1-1.clar"

[contracts.arkadiko-vault-trait-v1]
depends_on = ["sip-010-trait-ft-standard"]
path = "contracts/external/arkadiko/arkadiko-vault-trait-v1.clar"

[contracts.arkadiko-vault-manager-trait-v1]
depends_on = ["arkadiko-vault-trait-v1", "arkadiko-collateral-types-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-vault-manager-trait-v1.clar"

[contracts.arkadiko-auction-engine-trait-v1]
depends_on = ["arkadiko-oracle-trait-v1", "arkadiko-vault-manager-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-auction-engine-trait-v1.clar"

[contracts.arkadiko-collateral-types-trait-v1]
depends_on = []
path = "contracts/external/arkadiko/arkadiko-collateral-types-trait-v1.clar"

[contracts.stdiko-token]
depends_on = []
path = "contracts/external/arkadiko/stdiko-token.clar"

[contracts.arkadiko-stake-pool-diko-trait-v1]
depends_on = []
path = "contracts/external/arkadiko/arkadiko-stake-pool-diko-trait-v1.clar"

[contracts.arkadiko-stake-pool-diko-v1-1]
depends_on = ["arkadiko-stake-pool-trait-v1", "arkadiko-stake-pool-diko-trait-v1", "arkadiko-token", "stdiko-token", "sip-010-trait-ft-standard", "arkadiko-stake-registry-v1-1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-diko-v1-1.clar"

[contracts.arkadiko-stake-pool-diko-slash-v1-1]
depends_on = ["arkadiko-stake-pool-diko-v1-1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-diko-slash-v1-1.clar"

[contracts.arkadiko-stake-pool-diko-usda-v1-1]
depends_on = ["arkadiko-stake-pool-trait-v1", "arkadiko-swap-token-diko-usda", "arkadiko-stake-registry-v1-1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-diko-usda-v1-1.clar"

[contracts.arkadiko-stake-pool-wstx-usda-v1-1]
depends_on = ["arkadiko-stake-pool-trait-v1", "arkadiko-swap-token-wstx-usda", "arkadiko-stake-registry-v1-1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-wstx-usda-v1-1.clar"

[contracts.arkadiko-stake-pool-wstx-diko-v1-1]
depends_on = ["arkadiko-stake-pool-trait-v1", "arkadiko-swap-token-wstx-diko", "arkadiko-stake-registry-v1-1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-wstx-diko-v1-1.clar"

[contracts.arkadiko-swap-v1-1]
depends_on = ["sip-010-trait-ft-standard", "arkadiko-swap-trait-v1", "wrapped-stx-token"]
path = "contracts/external/arkadiko/arkadiko-swap-v1-1.clar"

[contracts.arkadiko-swap-trait-v1]
depends_on = []
path = "contracts/external/arkadiko/arkadiko-swap-trait-v1.clar"

[contracts.arkadiko-swap-token-diko-usda]
depends_on = ["arkadiko-swap-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-swap-token-diko-usda.clar"

[contracts.arkadiko-swap-token-wstx-usda]
depends_on = ["arkadiko-swap-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-swap-token-wstx-usda.clar"

[contracts.arkadiko-swap-token-wstx-diko]
depends_on = ["arkadiko-swap-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-swap-token-wstx-diko.clar"

[contracts.wrapped-stx-token]
depends_on = ["sip-010-trait-ft-standard", "arkadiko-dao"]
path = "contracts/external/arkadiko/wrapped-stx-token.clar"

[contracts.arkadiko-stake-pool-trait-v1]
depends_on = ["sip-010-trait-ft-standard", "arkadiko-stake-registry-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-stake-pool-trait-v1.clar"

[contracts.arkadiko-stake-registry-trait-v1]
depends_on = ["sip-010-trait-ft-standard"]
path = "contracts/external/arkadiko/arkadiko-stake-registry-trait-v1.clar"

[contracts.arkadiko-stake-registry-v1-1]
depends_on = ["arkadiko-token", "arkadiko-stake-pool-trait-v1", "sip-010-trait-ft-standard", "arkadiko-stake-registry-trait-v1"]
path = "contracts/external/arkadiko/arkadiko-stake-registry-v1-1.clar"

[contracts.arkadiko-vault-rewards-v1-1]
depends_on = ["arkadiko-token"]
path = "contracts/external/arkadiko/arkadiko-vault-rewards-v1-1.clar"

[contracts.usda-token]
depends_on = ["sip-010-trait-ft-standard", "arkadiko-dao"]
path = "contracts/external/arkadiko/usda-token.clar"

[contracts.xstx-token]
depends_on = ["sip-010-trait-ft-standard"]
path = "contracts/external/arkadiko/xstx-token.clar"

[contracts.arkadiko-diko-init]
depends_on = ["arkadiko-token"]
path = "contracts/external/arkadiko/arkadiko-diko-init.clar"

[contracts.sip-010-trait-ft-standard]
depends_on = []
path = "contracts/external/arkadiko/sip-010-trait-ft-standard.clar"

[contracts.sip-10-ft-standard]
depends_on = []
path = "contracts/taral/sip-10-ft-standard.clar"

[contracts.taral-coin]
depends_on = ["sip-10-ft-standard"]
path = "contracts/taral/taral-coin.clar"